name: SkillAPI
main: com.sucy.skill.SkillAPI
version: 3.108
author: Eniripsa96
depend: [MCCore]
softdepend: [Vault]
loadbefore: [Quests]

permissions:
  skillapi.basic:
    description: access to skill trees and using skills
    default: true
  skillapi.backup:
    dscription: allows backing up the SQL database
    default: op
  skillapi.reset:
    description: access to resetting your class
    default: true
  skillapi.exp:
    description: access to gaining exp
    default: true
  skillapi.level:
    description: access to using the level and exp commands
    default: op
  skillapi.mana:
    description: access to using the mana command
    default: op
  skillapi.points:
    description: access to using the points command
    default: op
  skillapi.reload:
    description: access to using the reload command
    default: op
  skillapi.class:
    description: access to all classes
    default: op
  skillapi.skill:
    description: access to all skills
    default: op
  skillapi.lore:
    description: access to all lore commands
    default: op
  skillapi.force:
    description: access to force commands
    default: false
  skillapi.attrib:
    description: access to giving attribute points
    default: op

  skillapi.*:
    description: access to all commands
    default: op
    children:
      skillapi.basic: true
      skillapi.reset: true
      skillapi.exp: true
      skillapi.level: true
      skillapi.mana: true
      skillapi.points: true
      skillapi.reload: true
      skillapi.class: true
      skillapi.skill: true
      skillapi.lore: true